lukeed/uvu

docs/api.uvu.md
index.d.ts
src/index.js
test/uvu.js

feat: add beforeEach and afterEach hooks

---

src/assert.js

I'm just removing a function that is no longer called.

refactor: remove unused function

---

bench/index.js

- Jest uses JSDOM by default whereas the others don't
- also edits to the readme are based on my personal machine, where
_all_ of the tests run slower, it would probably be faster on yours
- There's probably other optimizations to be made here as Jest is
focused on usability out-of-the-box as opposed to being the most
performant out-of-the-box
- e.g. both AVA and Jest transpile code by default
- But a more faithful comparison should also take an average over
hundreds of runs, post-cache, and should use a large test suite, so
there's other problems with these benchmarks too
- this is just me making it a little bit closer with an optimization
I'm quite familiar with and instantly recognized was missing
Not trying to start a flame war about proper benchmarks, but figured I'd at least make …

chore: use jest --env=node for a more accurate comparison

---

src/index.js

If I just do inside a test:
```javascript
throw Error("Mesage");
```
I get this:
```
Message  (undefined)
```
Followed by the stack trace, instead of just getting `Message`. This is because the format function is expecting the error to have a string property `operator` to put after the message of the error.
This MR makes it so if that property is missing, we just skip it.

Made `operator` property on errors optional.

---

index.d.ts
src/diff.js
test/diff.js

By default, `JSON.stringify` hides `undefined` and `NaN` values. 
This can be _super_ annoying when your assertion fails correctly, but doesn't show you the reason(s) why. Take these comparisons for example:
You can see that direct, simple comparisons (via `assert.is`) are fine. But any instances within complex values (object, arrays) were lost. AKA, the `{ foo: NaN }` was _printed_ as `{ foo: null }` -- hence grey text. We see this again with the last assertion with `{ foo: null }` ... and then `{ foo: undefined }` is hidden entirely, leaving an empty `Expected:` block.
After these changes, `undefined` and `NaN` are printed in the diff'ing output so that we have true data representations~!

fix(diff): retain `undefined` and `NaN` in output

---

src/index.d.ts

You don't pass a `suite` to the suite method, you pass a `context`. 👀

fix: type defs for a `suite` takes a context

---

src/diff.js
test/diff.js

Currently comparing with an empty strings throws following error:
```
TypeError: Cannot read property 'count' of undefined
at chars (/..../node_modules/uvu/diff/index.js:95:36)
```

diff: fix empty string handling

---

src/index.d.ts

I want to share my `tests`. Kind of to create this _partial_ concept. And for that, I would like my types to "accept" a `Test` type.

feat: also export the type `Test`

---

src/index.d.ts
src/index.js
test/suite.js

This PR aims to also pass through the name of either the suite or the test through to hooks.
This would aid in things like `playwright` and taking a screenshot after every test, and naming it the same as the test.

feat: also pass the name of the things to hooks

---

src/index.js

Hi!
I tried running `uvu` with [vite](https://github.com/vitejs/vite) and because `vite` injects `env` on to `window.process`, `uvu` would fail for me at `process.argv.some()`.
Other front end tools also sometimes override `process` so that client code can [grab ENV variables](https://cli.vuejs.org/guide/mode-and-env.html#using-env-variables-in-client-side-code).
Thanks for creating `uvu`, it's great!

Stricter isNode check

---

run/index.js
run/index.mjs
src/index.js
test/uvu.js

Moves `QUEUE` to the `globalThis` scope.
This guarantees that "both halves" of `uvu` are using the same internal value, as described in #69
With the linked reproduction, applying this PR required no other changes in order for the reproduction to work. Additionally, these combinations all worked out of the box:
* `uvu -r esm tests` on Node 14 (default)
* ^^^ + `"type": "module"` on Node 14
* `uvu tests` on Node 14 + `"type": "module"`
* `node -r esm tests/test.js` on Node 14
* ^^^ + `"type": "module"` on Node 14
* `node tests/test.js` on Node 14 + `"type": "module"`
The approach still works within browsers.
---
Closes #69

fix: move `QUEUE` to `globalThis` scope;

---

bin.js
src/parse.d.ts
src/parse.js
test/parse.js

* Fixes the types
* Adds `uvu/parse` tests
* Adds default to `opts.cwd`
* Returns new `requires` boolean indicating whether or not `-r/--require` was defined
_Better here than doing it differently inside `bin.js` directly._
---
Related to #72 – but **does not** replace #73
We'll see what other conditions can still trigger `ERR_UNKNOWN_FILE_EXTENSION` error and go from there with concrete example(s). I _suspect_ it's still possible to be thrown, but not sure exactly how. @tolu Let's keep both of your items open so that if/when any issues still arise, we already have a billboard and a springboard for them.

fix(parse): Add `cwd` default; return `requires` boolean

---

src/assert.js

Replaces `arr.map()` with a for-loop to avoid a "Max call stack size exceeded" error for fixtures with *many* lines to dedent.
Closes #115
Co-authored-by: @lukeed

replace `arr.map()` with for-loop to avoid stack overflow

---

docs/esm.md

Hi,
sorry if the changes are incorrect, but...
It's weird that it says that you should avoid `.mjs` and in the next paragraph that you "must use" `.mjs`. 😄 
Not sure if just removing it is the best way, though.

Fix copy & paste issue in ESM docs

---

src/assert.d.ts

This changes the return type of `assert.ok` from `void` to `asserts actual`, making type narrowing work:
```ts
type A = {ok: true, data: any} | {ok: false};
const a = {ok: true, data: 1} as A;
assert.ok(a.ok);
a.data; // type error! without this change, type does not narrow
```
This is the same as [`assert.ok` in `@types/node`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/46b370ffd2c8e81b21fac6a50f85be7a32d70efc/types/node/assert.d.ts#L62):
```ts
function ok(value: any, message?: string | Error): asserts value;
```
This is more complicated for `assert.not.ok`. The syntax `asserts !val` does not work, you have to say `asserts val is $type`. So, does a falsy union type like `asserts actual is false | '' | null | undefined | 0 | -0 | typeof NaN` work correctly for all cases? It …

change assert.ok to narrow the type

---

docs/api.assert.md

Hello!
On [assert documentation](https://github.com/lukeed/uvu/blob/master/docs/api.assert.md), there is no mention of `assert.match` and `assert.not.match`. So, I've added those along with some simple examples.
Thanks!

docs: added information for assert.match and assert.not.match

---

docs/api.uvu.md

Super minor, but link location was outdated/non-functional

docs: Correcting link in API docs

---

src/diff.js
test/assert.js

This PR addresses an issue where asserting arrays with non-arrays would crash the diff code instead of throwing an assertion error.
Fixes #178

Fix exception in diff code with arrays

---

src/index.d.ts

The types for `test.run()` say that it returns a function, but it actually has no return value.

fix(types): fix erroneous return type for `run`

---

src/diff.js
test/diff.js

Closes #175.
I used the more complex check of `Object.prototype.toString.call(val) === '[object BigInt]'` instead of just doing `typeof val === 'bigint'` to account for anyone doing something absurd like `Object(2n)` or `Object(BigInt(3)` just to cover all the bases.
Also may kinda smell that this is happening within `circular()`, but I didn't want to do anything more expansive than that. 😅
I [followed the lead of MDN and used `toString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#use_within_json) as the JSON-friendly output. When you run `console.log` on a `BigInt` it prints it with a trailing `n` to signify it is a special value. I could maybe see doing that instead for clarity? They'd still have to be a string though so the effect isn't …

Detect BigInt within circular() and properly convert within JSON.stringify

---

src/assert.d.ts

This changes will improve TypeScript support:
1. User will have autocomplete in tests:
2. Refactoring will be a little easier since test will help you guide what types you need to update (refactoring will be a little faster).

Connect `actual` and `expects` types in `equal()` and `is()`
